name: KP
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda
  - cudatoolkit
  - gdal
  - numpy
  - pandas
  - shap
  - matplotlib
  - scikit-learn
  - optuna
  - xgboost
