name: lsm-project-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda
  - cudatoolkit
  - gdal
  - numpy
  - pandas
  - tqdm
  - shap
  - matplotlib
  - scikit-learn
  - seaborn
# conda env create -f environment.yml
# conda activate lsm-project-env
